name: Update RSS Feed

on:
  workflow_dispatch:  # Trigger manually from the GitHub Actions tab
  schedule:
    - cron: '0 * * * *'  # This will run every hour

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedgen

      - name: Generate RSS Feed
        run: |
          python generate_rss_feed.py  # Ensure your script outputs to the correct path

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add rss-feeds/rss-feed_promo.xml
          git commit -m "Update RSS feed"
          git push
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
